[book]
authors = ["samarixum"]
language = "en"
src = "src"
title = "Remake Engine Docs"
multilingual = false
[output.html]
default-theme = "Coal"
preferred-dark-theme = "Ayu"
git-repository-url = "https://github.com/yggdrasil-au/RemakeEngineDocs"
edit-url-template = "https://github.com/yggdrasil-au/RemakeEngineDocs/edit/main/src/{path}"
